name: ignite
description: Tocca il futuro concretamente oggi e aiuta un intera comunità con un gesto che può fare la differenza.
version: 1.1.0

environment:
  sdk: ">=2.12.0 <3.2.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: any
  google_maps_flutter: any
  flutter_login: any
  geolocator: any
  curved_navigation_bar: any
  firebase_auth: any
  firebase_database: any
  expandable: any
  introduction_screen: any
  flutter_svg: any
  theme_provider: any
  cloud_firestore: any
  font_awesome_flutter: any
  http: any
  google_sign_in: any
  flutter_facebook_auth: any
  simple_gravatar: ^1.0.5
  auto_size_text: any
  pk_skeleton_null_safe: any
  sliding_up_panel: any
  datetime_picker_formfield: any
  url_launcher: any
  flutter_flushbar: any
  flare_flutter: any
  # quick_actions: ^0.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/general/intro.flr
    - assets/general/faqFireman.json
    - assets/general/faqCitizen.json
    - assets/general/map_style_main.json
    - assets/general/map_style_dark.json
    - assets/images/marker_1.png
    - assets/images/marker_2.png
    - assets/images/logo.png
    - assets/images/logo_height.png
    - assets/images/icon.png
    - assets/images/not_found.svg
    - assets/images/introduction/1.svg
    - assets/images/introduction/2.svg
    - assets/images/introduction/3.svg
    - assets/images/introduction/4.svg
    - assets/images/introduction/5.svg
    - assets/general/find.flr
    - assets/general/gps_rotation.flr
    - assets/general/maps.flr
    - assets/general/user.flr
    - assets/images/profile_ignite.png
    - assets/images/profile_google.png
    - assets/images/profile_facebook.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
